/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package warmingup.part1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] arsg) {
        App app = new App();

        // truncate test method
        String truncateString = app.truncate("hello Victor", 2);
        System.out.println("Truncate method output: " + truncateString);
        // parseYesOrNo test method
        boolean parseYesOrNoString = app.parseYesOrNo("yes");
        System.out.println(parseYesOrNoString);
        // getFizzBizz test method
        String getFizzBizzString = app.getFizzBuzz(15);
        System.out.println(getFizzBizzString);
    }

    public String truncate(String text, int maxLength) {

        if (text.length() > maxLength) {
            text = text.substring(0, maxLength);
        }
        return text;
    }

    public boolean parseYesOrNo(String text) {
        // FIXME: this seems to always return false, even when the `text` is "yes"

        if (text.toLowerCase().equals("yes")) {
            return true;
        }
        return false;
    }

    public String getFizzBuzz(int number) {
        if (number % 3 == 0 && number % 5 == 0) {
            return "fizzbuzz";
        } else if (number % 3 == 0) {
            return "fizz";
        } else if (number % 5 == 0) {
            return "buzz";
        } else {
            return Integer.toString(number);
        }
        // TODO: implement this method
    }
}
